[general]
shuffle_caption = false
caption_extension = '.txt'
keep_tokens = 1

[[datasets]]
resolution = 512
batch_size = 1
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = '/home/keke/fluxgym/datasets/caland'
  class_tokens = 'California landscape'
  num_repeats = 10